# Generated by Django 2.2.1 on 2019-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
